# Generated by Django 4.2.3 on 2023-07-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('banco', models.CharField(choices=[('BB', 'Banco do Brasil'), ('CE', 'Caixa Econômica Federal'), ('IT', 'Itaú Unibanco'), ('BR', 'Bradesco'), ('SB', 'Santander Brasil'), ('SF', 'Banco Safra'), ('BV', 'Banco Votorantim'), ('CI', 'Banco Citibank'), ('BTG', 'Banco BTG Pactual'), ('OR', 'Banco Original'), ('PA', 'Banco Pan'), ('IN', 'Banco Inter'), ('C6', 'Banco C6'), ('BNB', 'Banco do Nordeste do Brasil'), ('BCOOP', 'Bancoob (Banco Cooperativo do Brasil)'), ('SICREDI', 'Sicredi (Sistema de Crédito Cooperativo)'), ('BI', 'Banco Industrial do Brasil'), ('PINE', 'Banco Pine'), ('BANRISUL', 'Banco do Estado do Rio Grande do Sul (Banrisul)'), ('REN', 'Banco Rendimento')], max_length=8)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('valor', models.FloatField()),
                ('icone', models.ImageField(upload_to='icones')),
            ],
        ),
    ]
