# Generated by Django 4.2.3 on 2023-07-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('BB', 'Banco do Brasil'), ('CE', 'Caixa Econômica Federal'), ('IT', 'Itaú Unibanco'), ('BR', 'Bradesco'), ('SB', 'Santander Brasil'), ('SF', 'Banco Safra'), ('BV', 'Banco Votorantim'), ('CI', 'Banco Citibank'), ('BTG', 'Banco BTG Pactual'), ('OR', 'Banco Original'), ('PA', 'Banco Pan'), ('IN', 'Banco Inter'), ('C6', 'Banco C6'), ('BNB', 'Banco do Nordeste do Brasil'), ('BCOOP', 'Bancoob'), ('SICREDI', 'Sicredi'), ('BI', 'Banco Industrial do Brasil'), ('PINE', 'Banco Pine'), ('BANRISUL', 'Banrisul'), ('REN', 'Banco Rendimento')], max_length=8),
        ),
    ]
